loop_cadence_minutes: 60
population_size: 50
candidate_generation_N: 100
top_k_selection: 5
delta_metric_threshold: 0.001
token_budget_usd_monthly: 10.0
llm_proposer_breadth: "gpt-4o-mini"
llm_proposer_depth: "gpt-4o-pro"
llm_critic: "gpt-4o-pro"
output_modes:
  aligned_checkpoint_dir: "checkpoints/"
  eval_report_dir: "reports/eval/"
  audit_log_db_file: "logs/audit.duckdb"
